In [ ]:
import os
import pandas as pd
import numpy as np

In [15]:
dataset_path = 'opsd_germany_daily.csv'

opsd_daily = pd.read_csv(dataset_path, index_col='Date', parse_dates=True)
opsd_daily.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4383 entries, 2006-01-01 to 2017-12-31
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Consumption  4383 non-null   float64
 1   Wind         2920 non-null   float64
 2   Solar        2188 non-null   float64
 3   Wind+Solar   2187 non-null   float64
dtypes: float64(4)
memory usage: 171.2 KB

In [17]:
# Extract year, month, and weekday name from the index and assign them to new columns
opsd_daily['Year'] = opsd_daily.index.year
opsd_daily['Month'] = opsd_daily.index.month
opsd_daily['Weekday Name'] = opsd_daily.index.day_name()

# Display a random sampling of 5 rows
opsd_daily.sample(5, random_state=0)

            Consumption    Wind    Solar  Wind+Solar  Year  Month Weekday Name
Date
2008-08-23     1152.011     NaN      NaN         NaN  2008      8     Saturday
2013-08-08     1291.984  79.666   93.371     173.037  2013      8     Thursday
2009-08-27     1281.057     NaN      NaN         NaN  2009      8     Thursday
2015-10-02     1391.050  81.229  160.641     241.870  2015     10       Friday
2009-06-02     1201.522     NaN      NaN         NaN  2009      6      Tuesday

In [18]:
opsd_daily.loc['2017-08-10':'2017-08-11']

            Consumption     Wind   Solar  Wind+Solar  Year  Month Weekday Name
Date
2017-08-10     1351.491  100.274  71.160     171.434  2017      8     Thursday
2017-08-11     1329.039  108.577  42.198     150.775  2017      8       Friday

            Consumption     Wind   Solar  Wind+Solar  Year  Month Weekday Name
Date
2012-01-01      948.128  227.465   6.587     234.052  2012      1       Sunday
2012-01-02     1269.581  207.327   6.574     213.901  2012      1       Monday
2012-01-03     1334.745  473.468  24.679     498.147  2012      1      Tuesday
2012-01-04     1347.136  499.804  14.681     514.485  2012      1    Wednesday
2012-01-05     1376.658  523.851   5.071     528.922  2012      1     Thursday
...                 ...      ...     ...         ...   ...    ...          ...
2012-12-27     1068.617  302.195  13.111     315.306  2012     12     Thursday
2012-12-28     1109.424  152.562  24.007     176.569  2012     12       Friday
2012-12-29     1014.550  294.502  38.122     332.624  2012     12     Saturday
2012-12-30      936.786  412.921  27.255     440.176  2012     12       Sunday
2012-12-31      969.810  446.492  25.097     471.589  2012     12       Monday

[366 rows x 7 columns]

In [24]:
opsd_daily['Wind']

Date
2006-01-01        NaN
2006-01-02        NaN
2006-01-03        NaN
2006-01-04        NaN
2006-01-05        NaN
               ...
2017-12-27    394.507
2017-12-28    506.424
2017-12-29    584.277
2017-12-30    721.247
2017-12-31    721.176
Name: Wind, Length: 4383, dtype: float64

In [ ]:
dataset_path = 'IMDB-Movie-Data.csv'

data = pd.read_csv(dataset_path, index_col='Title')
data

In [ ]:
data.info()

In [ ]:
data.describe()

In [ ]:
series = data['Genre']
dataframe = data[['Genre']]

In [ ]:
series

In [ ]:
dataframe

In [ ]:
filtered_data = data.loc[(data['Genre'].str.contains('Action'))
      & (data['Rating'] > 6.0)
      & (data['Revenue (Millions)'] > data['Revenue (Millions)'].quantile(0.9)
    )]

In [ ]:
data.groupby('Director')[['Rating']].mean().sort_values('Rating', ascending=False)

In [ ]:
data.isnull().sum()

In [ ]:
data.drop(['Metascore', 'Revenue (Millions)'], axis=1)

In [ ]:
data.dropna()

In [ ]:
def rating_function(x):
    if x >= 6.0:
        return "good"
    else:
        return "bad"
    
data['Rating_category'] = data['Rating'].apply(rating_function)
data